# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8602b50eefdb1152a305c1dd3ef30e46fe4bc7f4d4774b2a91300b627b049ac0c710446454ef83753407ee98e56977763e424538b3899fe5836fb74aff5a9ed

test:
  secret_key_base: 34f2ed69ecaa22c2de9ebb2b5429f747204b16acad5becb9cddfdbc05dadda5c904c93545319b2459e7b939da1733fd00d7e2954f902732bc1498ab0cc581a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
